### ISSUE TITLE
Search selection needs improvement

### ISSUE THREAD

**Issue by nikimullick** [fossasia/susi_android#130]
- [ ] Once the **search** is done and closed, the text **remains selected**(coloured).It doesn't go away!! Unless a new search is started.

- [ ] Selection varies on User and Susi's side-The search selection is coloured(black background) on the user side but the text comes in black on susi's side.It must be the same kind on both sides
Similar issue was there #108 but seems like it was solved only on the user's end of chat.

![screenshot_2016-10-10-17-20-44-588_org fossasia susi ai 1](https://cloud.githubusercontent.com/assets/20987692/19235224/06c6dcb2-8f0e-11e6-94f7-4076234d7a96.png)

![screenshot_2016-10-10-17-28-36-848_org fossasia susi ai 1](https://cloud.githubusercontent.com/assets/20987692/19235513/c2d0ff4a-8f0f-11e6-9fd0-7dbefee9e4b6.png)

**Comment by jig08** [comment]
@nikimullick Nice find. Fix this pls.

**Comment by jig08** [comment]
Also see if PR https://github.com/fossasia/susi_android/pull/129 doesn't clash with your fix.

**Comment by nikimullick** [comment]
okay .I'll see to that

**Comment by amitiwary999** [comment]
@nikimullick have you fixed it? #108 was assigned to me and I forgot to change susi message background.I solved it so I am sending PR.

**Comment by nikimullick** [comment]
cool @amitiwary999  you can solve **2**. I'll do the other one in search.

**Comment by jig08** [comment]
@nikimullick @amitiwary999 Edited the initial issue to accommodate both.

**Comment by amitiwary999** [comment]
@nikimullick I am not getting your first point.

**Comment by nikimullick** [comment]
@jig08 seems like today isn't my day :( That search issue is solved in the new commit .

**Comment by the-dagger** [comment]
@nikimullick Point 1 isn't solved yet.
@amitiwary999 's PR solves only Point 2 of the issue.
You can work on this if you want to .

**Comment by amitiwary999** [comment]
@the-dagger point 1 is not a issue it is working fine in my android phone.

**Comment by nikimullick** [comment]
@the-dagger point 1 is already resolved.I don't know by whom but it is not there now in the latest commit.However, a little while ago it was an issue .Now,its working fine

**Comment by amitiwary999** [comment]
@nikimullick always try to update your code with master branch of fossasia/susi_android.

**Comment by nikimullick** [comment]
I did but meanwhile some other commits happened

**Comment by the-dagger** [comment]
Yes, its not happening with me too.
Closing this.
